### ISSUE TITLE
Pari kommenttia lukuun 4

### ISSUE THREAD

**Issue by mluukkai** [kasper/masters-thesis#1]
Sivu 22, toisessa kappaleessa:

_There is a clear distinction between embedded software and embedded systems [KRM+13]. The former is constrained by the hardware, but the latter is not only constrained by the hardware itself, but also by the development process of hardware._

Tuon merkitys jää hieman ilmaan. Samoin:

_My perspective emphasises on the hardware development process as a key part of software development in embedded systems._

Ja seuraava (s 24, luku 4.3. toinen kappale):

_Although cloud computing currently is applied in delivering software to the web, these techniques can be applied basically to any product that is able to collect and provide data about its usage ... For example cars can collect real-time fuel consumption data and telecom devices real-time bandwidth data [Bos12]. Previously these points of inter- est where only collected for management purposes, now they are used for development purposes._

Seuraava toistaa osin jo edellisen sivun lopussa todetun asian (s 25, toinen kappale):

_Remote deployments are possible on embedded systems_

**Comment by kasper** [comment]
Korjattu.
